services:
  - type: web
    name: ipchat
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /ping
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "22"
